"""Regenerate ``notebooks/README.md`` — an index of every demo notebook.

For each ``*.ipynb`` file under ``notebooks/``, the script reads a
``metadata.demo_info`` block (set by the notebook's builder) and emits
a one-row table entry with title, summary, runtime, cost, and
prerequisites. Falls back gracefully for notebooks that don't yet
declare ``demo_info`` — they appear with their first H1 markdown cell
as the title and the rest of that cell as the summary, so the index
remains useful even for in-flight notebooks that haven't adopted the
metadata key yet.

Invoked by ``make notebooks-readme``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOKS_DIR = REPO_ROOT / "notebooks"
README_PATH = NOTEBOOKS_DIR / "README.md"


def _first_paragraph(text: str) -> str:
    """Return the first non-empty paragraph from a markdown blob,
    collapsing internal newlines so the table row stays one line."""
    for chunk in text.strip().split("\n\n"):
        chunk = chunk.strip()
        if not chunk:
            continue
        # Drop a leading "# Title" if present
        first_line = chunk.split("\n", 1)[0]
        if first_line.startswith("#"):
            rest = chunk.split("\n", 1)
            if len(rest) > 1:
                chunk = rest[1]
            else:
                continue
        return " ".join(chunk.split())
    return ""


def extract_demo_info(nb_path: Path) -> dict[str, object]:
    """Pull the demo_info dict from notebook metadata, with sensible
    fallbacks for notebooks that don't declare it yet."""
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    metadata = nb.get("metadata", {})
    info: dict[str, object] = dict(metadata.get("demo_info", {}))

    # Fallback title: first H1 in a markdown cell.
    if "title" not in info:
        for cell in nb.get("cells", []):
            if cell.get("cell_type") != "markdown":
                continue
            src = cell.get("source", "")
            text = "".join(src) if isinstance(src, list) else src
            for line in text.splitlines():
                line = line.strip()
                if line.startswith("# "):
                    info["title"] = line[2:].strip()
                    break
            if "title" in info:
                break
    info.setdefault("title", nb_path.stem.replace("_", " ").title())

    # Fallback summary: first paragraph below the title.
    if "summary" not in info:
        for cell in nb.get("cells", []):
            if cell.get("cell_type") != "markdown":
                continue
            src = cell.get("source", "")
            text = "".join(src) if isinstance(src, list) else src
            para = _first_paragraph(text)
            if para:
                info["summary"] = para
                break
    info.setdefault("summary", "(no description)")
    info.setdefault("runtime_offline", "—")
    info.setdefault("runtime_live", "—")
    info.setdefault("estimated_cost", "—")
    info.setdefault("prerequisites", [])
    return info


def _prereq_text(prereqs: object) -> str:
    if isinstance(prereqs, list):
        return ", ".join(str(p) for p in prereqs) if prereqs else "—"
    return str(prereqs) if prereqs else "—"


def render_readme(notebooks: list[tuple[Path, dict[str, object]]]) -> str:
    lines = [
        "# Notebooks",
        "",
        "Auto-generated index of demo notebooks. Each notebook is "
        "self-contained — open it directly to read along, or run "
        "`make notebook-smoke` to execute the demo notebook end-to-end "
        "in cassette mode (no API key needed).",
        "",
    ]
    if not notebooks:
        lines.append("_(no notebooks yet)_")
        lines.append("")
    else:
        for nb_path, info in notebooks:
            rel = nb_path.relative_to(NOTEBOOKS_DIR)
            lines.append(f"## [{info['title']}]({rel.as_posix()})")
            lines.append("")
            lines.append(str(info["summary"]))
            lines.append("")
            lines.append("| Field | Value |")
            lines.append("| --- | --- |")
            lines.append(f"| Runtime (offline) | {info['runtime_offline']} |")
            lines.append(f"| Runtime (live) | {info['runtime_live']} |")
            lines.append(f"| Estimated cost | {info['estimated_cost']} |")
            lines.append(f"| Prerequisites | {_prereq_text(info['prerequisites'])} |")
            lines.append("")
    lines.append(
        "_This file is generated by `scripts/generate_notebooks_readme.py`. "
        "Run `make notebooks-readme` after adding or removing notebooks._"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    if not NOTEBOOKS_DIR.is_dir():
        print(f"notebooks directory not found: {NOTEBOOKS_DIR}")
        return 1
    nb_files = sorted(NOTEBOOKS_DIR.glob("*.ipynb"))
    entries = [(p, extract_demo_info(p)) for p in nb_files]
    README_PATH.write_text(render_readme(entries), encoding="utf-8")
    print(f"wrote {README_PATH.relative_to(REPO_ROOT)} "
          f"({len(entries)} notebook{'s' if len(entries) != 1 else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
